### ISSUE TITLE
Tests failing because of wheel installation error

### ISSUE THREAD

**Issue by sjkingo** [sjkingo/virtualenv-api#24]
@rmb938: there is a failure in the tests because it can't find `MarkupSafe` to install as a wheel (a dependency of flask). It's definitely on pypi and I can install it successfully.

Build log is here: https://travis-ci.org/sjkingo/virtualenv-api/jobs/119961786

The pip output says it's ignoring indexes and using cache only? What's the `--no-index` flag to pip for in this instance?

Would you be able to take a look and see if you can fix?

**Comment by rmb938** [comment]
The ```--no-index``` ignores the pypi package repo and instead looks in the ```--find-links``` directory to install things from. 

 Inside ```/tmp/wheelhouse``` should be the wheel for the MarkupSafe package but I am guessing it is not there.  

I can do some testing this weekend to figure out what is breaking.

**Comment by sjkingo** [comment]
What's the advantage of using --no-index - wouldn't we want it to check
/tmp/wheelhouse first, and if it's not there, fall back to PyPi?

**Comment by rmb938** [comment]
Well in that test we are testing the wheeling functionality. So we wheel up the package then we try and install it from that wheel. 

I see your point where falling pack to PyPi makes sense however that functionality isn't built into pip install. So if we get rid of ```--no-index``` everything will go from PyPi instead of trying to install from the wheelhouse directory.

**Comment by rmb938** [comment]
Something much of changed recently to make that test fail as I believe it was working fine back when we added the wheel functionality.

**Comment by sjkingo** [comment]
Yes I agree that it was working originally - but with no commits (and hence tests run) in 8 months I'm not sure when or with what version of pip! Defeats the purpose of CI somewhat...

If you wouldn't mind having a look to see why the MarkupSafe wheel isn't being created that would be good.

**Comment by rmb938** [comment]
Yup I will take a look. If you can give me until tomorrow I should be able to have a solution or a workaround by then.

**Comment by sjkingo** [comment]
No worries, thank you

**Comment by rmb938** [comment]
Well I have some bad news. No matter what I do I can't see to replicate the error from travis. The tests run, without errors, running wheel manually works fine and creating a small test script works as well. The only thing I could think of is the travis build is running in a debian container vs my centos machine ... but really that shouldn't matter much if at all.

I will try and do some more testing but if I can't see to replicate it then I am kinda clueless.

**Comment by sjkingo** [comment]
Thanks for trying to reproduce. Must be something to do with the Travis
infrastructure then. I'll have a look and see.

**Comment by sjkingo** [comment]
Thanks for the push, that fixed it!

**Comment by sjkingo** [comment]
Oops; wrong thread..

Either way, we're all good now.
