### ISSUE TITLE
Support editable installation

### ISSUE THREAD

**Issue by voidpp** [sjkingo/virtualenv-api#27]
pip help:
>  Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.

As I see, this is not possible now with the virtualenv-api.
I tried `env.install("-e /path/to/module")`, but it raised an exception.

(virtualenv-api==2.1.9)

BTW this package is pretty cool :)

**Comment by sjkingo** [comment]
Thanks for picking this up. Version 2.1.10 is now available on pypi which fixes this.

```
>>> env.install('-e git+https://github.com/stephenmcd/cartridge.git')
```

(or any other valid URL/path)

**Comment by voidpp** [comment]
Wow, thx for the quick response and release.
