### ISSUE TITLE
Shebang length exceeded in pip executable

### ISSUE THREAD

**Issue by rmb938** [sjkingo/virtualenv-api#30]
See the following issue on pip: https://github.com/pypa/pip/issues/1773

The accepted solution seems to be running the following:

```
/some/path/to/python -m pip
```

I would make a PR but I am not sure on how you want to go about supporting that.

**Comment by sjkingo** [comment]
An interesting problem that I'd never considered. Have you run into this personally?

If we could have some tests that show it breaks with paths longer than `BINPRM_BUF_SIZE`, and changing the invocation of `pip` to run as a module doesn't break anything, that should be OK.

Could we just change `_pip_rpath()` to instead search for the `python` executable and return that `+ ['-m', 'pip']`?

**Comment by rmb938** [comment]
Yea, I am running into it while testing an application in jenkins that just happens to have really long path names.

I can get those changes in and a pull request made.

**Comment by sjkingo** [comment]
Awesome, thank you Ryan. I have released version 2.1.13 that includes this fix.
